--- # 监控配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  # 设置 Spring Boot Admin Server 地址
  url: http://ruoyi-monitor-admin:9090/admin
  instance:
    service-host-type: IP
  username: ruoyi
  password: 123456
